POST https://ao2jyzs9o3.execute-api.eu-west-1.amazonaws.com/prod/wine-list
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "userId": "xxx",
  "name": "A Wine",
  "style": "red",
  "country": "France",
  "region": "Burgundy",
  "vineyard": "Somewhere",
  "vintage": 2016,
  "score": 98,
  "flavourProfile": ["Cherry, Ash, Bark"]
}

###

PUT https://ao2jyzs9o3.execute-api.eu-west-1.amazonaws.com/prod/wine-list/xxx/WINE%23TgfVdBcCRlgeDLpsTXzsQ
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "userId": "xxx",
  "name": "A Nice Wine",
  "style": "red",
  "country": "France",
  "region": "Burgundy",
  "vineyard": "Somewhere",
  "vintage": 2016,
  "score": 98
}

###

PUT https://ao2jyzs9o3.execute-api.eu-west-1.amazonaws.com/prod/wine-list/xxx/tasting-note
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "userId": "xxx",
  "wineSk": "WINE#JframkHlDzQTjrOFvubBw",
  "text": "blah blah blah"
}

###

PUT https://ao2jyzs9o3.execute-api.eu-west-1.amazonaws.com/prod/wine-list/xxx/select-tasting-note
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "userId": "xxx",
  "wineSk": "WINE#JframkHlDzQTjrOFvubBw",
  "tastingNoteSk": "WINE#JframkHlDzQTjrOFvubBw_NOTE#V6vWF7eiLTqKDG-aIefj9"
}

###

DELETE https://ao2jyzs9o3.execute-api.eu-west-1.amazonaws.com/prod/wine-list/xxx/A-Wine+F6qPZ5KCG4ZpqRO0GBvQR
Authorization: Bearer {{apiKey}}

###

GET https://ao2jyzs9o3.execute-api.eu-west-1.amazonaws.com/prod/wine-list/xxx/WINE#JframkHlDzQTjrOFvubBw
Content-Type: application/json
Authorization: Bearer {{apiKey}}

###

GET https://ao2jyzs9o3.execute-api.eu-west-1.amazonaws.com/prod/wine-list/xxx
Content-Type: application/json
Authorization: Bearer {{apiKey}}

###
