POST https://ao2jyzs9o3.execute-api.eu-west-1.amazonaws.com/prod/tasting-notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InpZU2UyQk5DLWFNY1Z4NFlfb1ZSeCJ9.eyJpc3MiOiJodHRwczovL2dwdC0zLWF1dGguZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYyZGFmNzRhOGI1MmM3ZjE3MDU5NzFmMiIsImF1ZCI6WyJodHRwczovL2dwdC0zLWRlbW8uY29tIiwiaHR0cHM6Ly9ncHQtMy1hdXRoLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NTg5NTQ0NTYsImV4cCI6MTY1OTA0MDg1NiwiYXpwIjoieEl0UjVicXJLbG4yZ0w3cFcwQ2VQVWV4TFBxb3NzMDciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.BQQORNK3aNAmXdsDvD66_qVnGpC8NVcbdNsvbnfKW2Otmkez2ToPexlpVe9FRdBQ0A6J97Qvwz3tql4_T--sfiBt3C7aREoujAASHY_8s8ItQRTZh5ZwDZTVYK8dZEpltlpjeDNQCR_TVaoQa2p9yUCLFG7zXZGYaXh8x8AWTcdRTjmXFIxaaTfeNhJdJOpa1Jyjdc47H9XLLLAoApZl9PgmfiIb_2zFY8b-fjbOJiWIwMGBP_neNB_zFmZkEHN1u_CcMP6SoJScoLf-9nN_S3BoM09NKFSVBkL7VMnVVHcn8er39IOGnOz8hnbkuZom57njDbRdcAEjqHd2C06qtw

{
  "prompt": "nice wine"
}

###

POST https://ao2jyzs9o3.execute-api.eu-west-1.amazonaws.com/prod/recommendations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InpZU2UyQk5DLWFNY1Z4NFlfb1ZSeCJ9.eyJpc3MiOiJodHRwczovL2dwdC0zLWF1dGguZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYyZGFmNzRhOGI1MmM3ZjE3MDU5NzFmMiIsImF1ZCI6WyJodHRwczovL2dwdC0zLWRlbW8uY29tIiwiaHR0cHM6Ly9ncHQtMy1hdXRoLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NTg5NTQ0NTYsImV4cCI6MTY1OTA0MDg1NiwiYXpwIjoieEl0UjVicXJLbG4yZ0w3cFcwQ2VQVWV4TFBxb3NzMDciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.BQQORNK3aNAmXdsDvD66_qVnGpC8NVcbdNsvbnfKW2Otmkez2ToPexlpVe9FRdBQ0A6J97Qvwz3tql4_T--sfiBt3C7aREoujAASHY_8s8ItQRTZh5ZwDZTVYK8dZEpltlpjeDNQCR_TVaoQa2p9yUCLFG7zXZGYaXh8x8AWTcdRTjmXFIxaaTfeNhJdJOpa1Jyjdc47H9XLLLAoApZl9PgmfiIb_2zFY8b-fjbOJiWIwMGBP_neNB_zFmZkEHN1u_CcMP6SoJScoLf-9nN_S3BoM09NKFSVBkL7VMnVVHcn8er39IOGnOz8hnbkuZom57njDbRdcAEjqHd2C06qtw

{
  "query": "Champagne Rosé"
}

###
